version: "3"

volumes:
  rabbitmq_data:
    external: false

networks:
  annotator_net:
    external: false

services:
  webserver:
    container_name: annotator_webclient
    build:
      context: .
      args:
        uid: 1001
        gid: 1001
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5000:5000
    environment:
      - SECRET_KEY=RandomSecretKeyHere
      - FLASK_APP=webserver
      - FLASK_ENV=production
      - DEBUG=false
      - LOG_LEVEL=debug
      - MONGODB_HOST=mongodb://database/dev
      - BROKER_URL=amqp://user:password@messageq:5672//
      - CELERY_RESULT_BACKEND=mongodb://database/dev
    volumes:
      - ./storage/datasets:/workspace/datasets
    depends_on:
      - database
      - workers
    networks:
      - annotator_net

  workers:
    container_name: annotator_workers
    build:
      context: .
      args:
        uid: 1001
        gid: 1001
      dockerfile: ./backend/workers/Dockerfile
    environment:
      - MONGODB_HOST=mongodb://database/dev
      - BROKER_URL=amqp://user:password@messageq:5672//
      - CELERY_RESULT_BACKEND=mongodb://database/dev
    volumes:
      - ./backend/config:/workspace/config
      - ./backend/webserver:/workspace/webserver
      - ./backend/workers:/workspace/workers
      - ./backend/database:/workspace/database
      - ./storage/datasets:/workspace/datasets
    depends_on:
      - messageq
      - database
    networks:
      - annotator_net

  messageq:
    image: rabbitmq:3
    container_name: annotator_message_q
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - annotator_net

  database:
    image: mongo:4.0
    container_name: annotator_mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./storage/mongo/db:/data/db
      - ./storage/mongo/configdb:/data/configdb
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null
    networks:
      - annotator_net
