# Backend environment docker image
FROM tensorflow/tensorflow:1.14.0-gpu-py3

# RUN apt-get update
# RUN apt-get install -y git

# WORKDIR /workspace/

# # Copy backend
# COPY ./backend/requirements.txt /workspace/

# # Install python package dependices
# RUN pip install -r requirements.txt && \
#     pip install "gunicorn[eventlet]==19.9.0" && \
#     pip install pycocotools

# RUN apt-get -y -o Dpkg::Options::="--force-confmiss" install --reinstall netbase
