# FROM python:3.6.8-slim

# RUN apt-get update && \
#     apt-get install -y --no-install-recommends openjdk-8-jre-headless dcmtk

# WORKDIR /workspace/

# COPY requirements.txt requirements.txt
# RUN pip install -r requirements.txt && \
#     pip install gunicorn[eventlet]==19.9.0 && \
#     pip install pycocotools